### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by philipp-lehmann** [KrabCode/LazyGui#244]
Hey there

The minimal example doesn't work under MacOS Silicon.
What am I missing?

Thanks for any help

MacOS Ventura 13.2 (22D49)
Processing v4.2

```

OpenGL error 1282 at bot beginDraw(): invalid operation
RuntimeException: Cannot validate shader program:
Validation Failed: Current draw framebuffer is invalid.
�
java.lang.RuntimeException: Cannot validate shader program:
Validation Failed: Current draw framebuffer is invalid.
�
	at processing.core.PGraphics.showException(PGraphics.java:8327)
	at processing.opengl.PShader.validate(PShader.java:954)
	at processing.opengl.PShader.init(PShader.java:911)
	at processing.opengl.PShader.getAttributeLoc(PShader.java:604)
	at processing.opengl.PShader.loadAttributes(PShader.java:1126)
	at processing.opengl.PGraphicsOpenGL.getPolyShader(PGraphicsOpenGL.java:7007)
	at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2343)
	at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2280)
	at processing.opengl.PGraphicsOpenGL.popProjection(PGraphicsOpenGL.java:4070)
	at processing.opengl.PGraphics2D.end2D(PGraphics2D.java:178)
	at processing.opengl.PGraphicsOpenGL.filter(PGraphicsOpenGL.java:6097)
	at com.krab.lazy.utils.SnapToGrid.displayGuideAndApplyFilter(SnapToGrid.java:65)
	at com.krab.lazy.LazyGui.draw(LazyGui.java:179)
	at com.krab.lazy.LazyGui.draw(LazyGui.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1309)
	at processing.core.PApplet.handleMethods(PApplet.java:1456)
	at processing.core.PApplet.handleDraw(PApplet.java:2106)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:840)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
RuntimeException: Cannot validate shader program:
Validation Failed: Current draw framebuffer is invalid.
�
```

**Comment by KrabCode** [comment]
Thanks for posting! 

Just for troubleshooting purposes:
- please update graphics drivers
- does a basic P3D sketch work for you, let's say with a cube on black background?

```
void setup(){
  size(600,600,P3D);
}

void draw(){
  float t = frameCount * 0.01;
  background(0);
  translate(width/2, height/2);
  rotateX(t);
  box(150);
}
```

**Comment by philipp-lehmann** [comment]
Hello Jakub

I just updated everything and can confirm that a regular P3D sketch runs fine.

Adding this is still ok:
```
import com.krab.lazy.*;
LazyGui gui;
```
Adding this line too throws the errors:
`gui = new LazyGui(this);`

**Comment by KrabCode** [comment]
Thanks!

I may have some ideas for what it could be, I'll try adding #version into shader files and maybe the first beginDraw() of any P2D Pgraphics is broken but I can do a dummy draw at initialization to work around that... 

I'll try to make a new release with these fixes soon, you will be able to update LazyGui from the pde and I'll ask you to try it then

**Comment by philipp-lehmann** [comment]
👍 ok, let me know if i can support you

**Comment by KrabCode** [comment]
the new release v1.1.3 attempts to fix it, could you update and try it again please?

![image](https://user-images.githubusercontent.com/25923016/236624813-99cb7007-370b-48ae-9f4d-5831b4e7f47c.png)

**Comment by KrabCode** [comment]
I suspect it's related to this issue and I'm using the workaround from the end there now.
```
graphics.beginDraw();
graphics.endDraw();
```
https://github.com/processing/processing4/issues/641

**Comment by philipp-lehmann** [comment]
Wow that was quick. Unfortunately for me it didnt solve the issue right away.
```

OpenGL error 1282 at bot beginDraw(): invalid operation
OpenGL error 1286 at top endDraw(): invalid framebuffer operation
OpenGL error 1286 at bot endDraw(): invalid framebuffer operation
RuntimeException: Cannot validate shader program:
Validation Failed: Current draw framebuffer is invalid.

java.lang.RuntimeException: Cannot validate shader program:
Validation Failed: Current draw framebuffer is invalid.

	at processing.core.PGraphics.showException(PGraphics.java:8327)
	at processing.opengl.PShader.validate(PShader.java:954)
	at processing.opengl.PShader.init(PShader.java:911)
	at processing.opengl.PShader.getAttributeLoc(PShader.java:604)
	at processing.opengl.PShader.loadAttributes(PShader.java:1126)
	at processing.opengl.PGraphicsOpenGL.getPolyShader(PGraphicsOpenGL.java:7007)
	at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2343)
	at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2280)
	at processing.opengl.PGraphicsOpenGL.popProjection(PGraphicsOpenGL.java:4070)
	at processing.opengl.PGraphics2D.end2D(PGraphics2D.java:178)
	at processing.opengl.PGraphicsOpenGL.filter(PGraphicsOpenGL.java:6097)
	at com.krab.lazy.utils.SnapToGrid.displayGuideAndApplyFilter(SnapToGrid.java:65)
	at com.krab.lazy.LazyGui.draw(LazyGui.java:184)
	at com.krab.lazy.LazyGui.draw(LazyGui.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1309)
	at processing.core.PApplet.handleMethods(PApplet.java:1456)
	at processing.core.PApplet.handleDraw(PApplet.java:2106)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:840)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
RuntimeException: Cannot validate shader program:
Validation Failed: Current draw framebuffer is invalid.


```

**Comment by KrabCode** [comment]
Alright, thanks for testing it. Afraid I'm out of quick fixes but I'll try to figure something out, maybe borrow a mac at work...

**Comment by pflouret** [comment]
@KrabCode The problem actually seems to be this https://github.com/processing/processing4/issues/694 (or, well, it could be both)

I commented out the `smooth(8)` call and it works fine after that.

**Comment by KrabCode** [comment]
Oh wow, that's huge, ok, thanks a lot.

`smooth(8)` is mentioned a couple of times in the project and it's not set in stone, so I'll extract all those magic 8s into a global constant, set it to 4 by default and probably also let the user set it themselves through the LazyGuiSettings. 

You can expect a fix coming out within 24 hours.

**Comment by KrabCode** [comment]
oops I didn't mean to close the issue, it seems like GitHub detected some keywords in my commit message.

**Comment by KrabCode** [comment]
The 1.2.0 update is live, released on github and available in the PDE, could you please try if it does indeed fix the problem?

**Comment by pflouret** [comment]
Seems to work fine for me via intellij!

**Comment by KrabCode** [comment]
Alright, seems to be fixed then! Thanks so much. 

I'd love for @philipp-lehmann to also confirm this before I close this issue.

**Comment by KrabCode** [comment]
Ok, since we got no response from OP I'm closing the issue. Feel free to reopen if it doesn't work.

**Comment by philipp-lehmann** [comment]
Can confirm that it works now, thanks for your work @KrabCode @pflouret 
Like to start using your library.

...

The grid effect when moving windows is so nice 👍
